# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Personal info
name: Saeed Hojjatpanah
title: Astronomer
email: saeed.Hojjatpanah@astro.up.pt
website: www.github.com

# Social links
twitter_username: SaeedHojjatpanah
github_username:  saeedm31
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
instagram_username: saeedhjd
# linkedin_username: jameswgran
# pinterest_username: jekyll
youtube_username: Saeed Hojjatpanah
# googleplus_username: +jekyll

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  Hi, my name's Saeed and I'm a PhD candidate in astronomy at University of Porto !

  

# Projects Section
# projects_title: Projects

# Experience Section
# experience_title: Experience

# Education Section
# educaton_title: Education

# More Section
# more_title: A Little More About Me
more_content: | # this will include new lines to allow paragraphs
  Alos :
   - Exoplanets
   - Transit

# Footer
footer_show_references: true

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
