# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Personal info
name: Saeed Hojjatpanah
title: Astronomer
email: saeed.Hojjatpanah[at]astro[dot]up[dot]pt
website: saeedm31.github.io

# Social links
twitter_username: SaeedHojjatpana
github_username:  saeedm31
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
instagram_username: saeedjjdo
# linkedin_username: jameswgran
# pinterest_username: jekyll
# youtube_username: Saeed Hojjatpanah
# googleplus_username: +jekyll

# About Section
# about_title: About Me
# about_profile_image: images/profile.jpg
about_profile_image: images/pro.jpg
about_content: | # this will include new lines to allow paragraphs
  Hi ! I am a PhD candidate in Astronomy at The Instituto de Astrofísica e\
   Ciências do Espaço (IA) and University of Porto.
   I am interested in detecting and characterizing new exoplanets.
  

# Projects Section
# projects_title: Projects

# Experience Section
# experience_title: Experience

# Education Section
# educaton_title: Education

# More Section
# more_title: A Little More About Me
more_content: | # this will include new lines to allow paragraphs
  ---
  TBD..
   
   

# Footer
footer_show_references: true

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
