# Site
encoding: UTF-8

repository: sproogen/resume-theme
favicon: images/favicon.ico

# Personal info
name: Saeed Hojjatpanah
title: Astronomer
email: saeed.Hojjatpanah[at]astro[dot]up[dot]pt
website: saeedm31.github.io

# Social links
twitter_username: SHojjatpanah
github_username:  saeedm31
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
instagram_username: saeedjjdo
# linkedin_username: jameswgran
# pinterest_username: jekyll
# youtube_username: Saeed Hojjatpanah
# googleplus_username: +jekyll

# About Section
# about_title: About Me
# about_profile_image: images/profile.jpg
about_profile_image: images/pro.jpg
about_content: | # this will include new lines to allow paragraphs
  Hi ! My name is Saeed and I am an astronomer working at <a href="https://www.lam.fr/?lang=en"> Laboratoire d’Astrophysique de Marseille (UMR7326 - CNRS-INSU, Université d’Aix-Marseille).
   I am interested in detecting and characterizing of Exoplanets using the both transit and radial velocity methods.

 
  


# Projects Section
projects_title: Refereed Publications

# Experience Section
# experience_title: Experience

# Education Section
# educaton_title: Education

# More Section
# more_title: A Little More About Me
more_content: | # this will include new lines to allow paragraphs
  I hold a bachelor's degree in Physics and a master’s degree in Astronomy from the University of Zanjan, Iran that investigated the Exoplanet detection survey using HARPS and K2 data.
   

# Footer
footer_show_references: true

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
